CREATE TABLE IF NOT EXISTS STEM_DATA (
    STUDENT_ID INT NOT NULL PRIMARY KEY,
    PROGRAM_CODE VARCHAR(4) NOT NULL,
    SUBPROGRAM_DESC TEXT NOT NULL,
    COURSE_DESC TEXT NOT NULL,
    COURSE_NUM VARCHAR(8) NOT NULL,
    FINAL_GRADE VARCHAR(2) NOT NULL,
    COURSE_SEMESTER VARCHAR(2) NOT NULL CHECK(COURSE_SEMESTER IN ('FA', 'SP')),
    COURSE_WORK_YEAR VARCHAR(4) NOT NULL,
    RAW INT,
    SCALED INT,
    ACHIEVEMENT_LEVEL VARCHAR(2)
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    ID INT NOT NULL PRIMARY KEY,
    LAST_NAME TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    MAJOR_1 TEXT NOT NULL,
    MAJOR_2 TEXT,
    MAJOR_3 TEXT,
    CONCENTRATION_1 TEXT,
    CONCENTRATION_2 TEXT,
    MINOR_1 TEXT,
    MINOR_2 TEXT,
    MINOR_3 TEXT,
    MATH_PLACEMENT_SCORE INT,
    HIGH_SCHOOL_GPA REAL,
    COLLEGE_GPA REAL,
    SAT_SCORE INT,
    ACT_SCORE INT,
    STATE_CODE VARCHAR(2) NOT NULL,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    LEAVE_DATE DATE,
    LEAVE_REASON TEXT,
    FIRST_GEN_STUDENT BOOLEAN,
    ETHNICITY TEXT,
    MCAS_SUBJECT TEXT
);

CREATE TABLE IF NOT EXISTS USERS (
    ID INT NOT NULL PRIMARY KEY,
    LAST_NAME TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL,
    HASH TEXT,
    SALT TEXT,
    IS_ADMIN BOOLEAN NOT NULL,
    PROVIDER VARCHAR(6) NOT NULL
);