on:
  pull_request:
    
  workflow_dispatch:

jobs:
  add-license-headers:
    name: Build and Run JUnit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          cd license-headers
          bash run.sh
      